deploy: .terraform
	terraform apply -input=false -auto-approve

plan-deploy: .terraform
	terraform plan

backend.tf:
	cp backend.example_tf backend.tf

#Apply supports setting values with TF_VAR, but TF_BACKEND_ is not, as of writing, supported by
#terraform
.terraform: backend.tf
	terraform init -backend-config="bucket=${TF_BACKEND_bucket}"
